### ISSUE TITLE
Exception on Huawei P20 

### ISSUE THREAD

**Issue by mathuld** [hughnatt/application-mobile-sans-nom#30]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ca.uqac.alterra, PID: 19051
    java.lang.SecurityException: my location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION
        at com.google.maps.api.android.lib6.impl.bm.c(:com.google.android.gms.dynamite_mapsdynamite@19530083@19.5.30 (100408-0):521)
        at com.google.android.gms.maps.internal.k.a(:com.google.android.gms.dynamite_mapsdynamite@19530083@19.5.30 (100408-0):273)
        at cl.onTransact(:com.google.android.gms.dynamite_mapsdynamite@19530083@19.5.30 (100408-0):5)
        at android.os.Binder.transact(Binder.java:675)
        at com.google.android.gms.internal.maps.zza.zzb(Unknown Source:20)
        at com.google.android.gms.maps.internal.zzg.setMyLocationEnabled(Unknown Source:109)
        at com.google.android.gms.maps.GoogleMap.setMyLocationEnabled(Unknown Source:112)
        at ca.uqac.alterra.MapsHandler.onMapReady(MapsHandler.java:57)
        at com.google.android.gms.maps.zzak.zza(Unknown Source:2)
        at com.google.android.gms.maps.internal.zzaq.dispatchTransaction(Unknown Source:12)
        at com.google.android.gms.internal.maps.zzb.onTransact(Unknown Source:12)
        at android.os.Binder.transact(Binder.java:675)
        at ck.b(:com.google.android.gms.dynamite_mapsdynamite@19530083@19.5.30 (100408-0):13)
        at com.google.android.gms.maps.internal.bc.a(:com.google.android.gms.dynamite_mapsdynamite@19530083@19.5.30 (100408-0):4)
        at com.google.maps.api.android.lib6.impl.bi.run(:com.google.android.gms.dynamite_mapsdynamite@19530083@19.5.30 (100408-0):4)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by hughnatt** [comment]
Ok je viens d'identifier le problème, my bad, ça doit foirer sur tous les types de téléphone
